name: Angular Dotnet CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        # Checkout repo into github runner
        - uses: actions/checkout@v3
        
        # Install Node Js - v20
        - uses: actions/setup-node@v3
          with:
            node-version: 20
        
        # Setup Angular 
        - name: Setup Angular
          run: | 
            npm install --prefix AngularApplication
            npm run build --prefix AngularApplication

        # Upload frontend build as artifact
        - name: Upload Angular Artifacts 
          uses: actions/upload-artifact@v4
          with:
            name: frontend-artifact
            path: AngularApplication/dist

        # Stepup .NET
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8

        # Build .NET backend
        - name: Build .NET API
          run: dotnet build DotnetApplication/DotnetApplication.csproj --configuration Release
  
  use-frontend-artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download Angular Artifact
      - uses: actions/download-artifact@v4
        with:
          name: frontend-artifact

      # List downloaded files
      - run: ls -R

      # Show index.html
      - run: cat */browser/index.html    