name: First Action For Testing

on:
  push:
    branches: [ "master" ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "GitHub Actions is working" > hello.txt

      - name: Show Dates
        run: date

      - name: Upload hello.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt