name: First Action For Testing

on:
  push:
    branches: [ "master" ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Create hello.txt
        run: echo "GitHub Actions is working" > hello.txt

      - name: Upload hello.txt
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt

      - name: Show Dates
        run: date

  use-artifact-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Download hello.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact

      - name: Show artifact content
        run: cat hello.txt