name: First Action For Testing

on:
  push:
    branches: [ "master" ]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Create and upload hello.txt
        run: |
          echo "GitHub Actions is working" > hello.txt
          # Upload artifact using GitHub CLI
          gh run upload-artifact hello.txt --name hello-artifact

      - name: Show Dates
        run: date

  use-artifact-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Download hello.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-artifact

      - name: Show artifact content
        run: cat hello.txt